[package]
name = "creditcoin3-rpc-core-trace"
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
license = "GPL-3.0-only"

[dependencies]
ethereum-types = { workspace = true, features = ["std"] }
futures = { workspace = true, features = ["compat"] }
jsonrpsee = { workspace = true, features = ["macros", "server"] }
creditcoin3-client-evm-tracing = { workspace = true }
creditcoin3-rpc-core-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
